create table if not exists public.blog_rank_targets (
  id uuid primary key default gen_random_uuid(),
  post_url text not null,
  blog_id text not null,
  log_no text not null,
  post_title text not null default '',
  keyword text not null,
  device text not null default 'desktop'
    check (device in ('desktop', 'mobile')),
  max_rank integer not null default 300
    check (max_rank between 100 and 1000),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (blog_id, log_no, keyword, device)
);

create table if not exists public.blog_rank_history (
  id bigint generated by default as identity primary key,
  target_id uuid not null references public.blog_rank_targets(id) on delete cascade,
  provider text not null
    check (provider in ('naver_blog_api', 'serpapi_nexearch')),
  rank integer,
  page integer,
  found boolean not null default false,
  checked_count integer not null default 0,
  result_title text not null default '',
  result_url text not null default '',
  collected_at timestamptz not null default now()
);

create index if not exists blog_rank_targets_active_idx
  on public.blog_rank_targets(active, updated_at desc);

create index if not exists blog_rank_history_target_provider_time_idx
  on public.blog_rank_history(target_id, provider, collected_at desc);

alter table public.blog_rank_targets enable row level security;
alter table public.blog_rank_history enable row level security;

comment on table public.blog_rank_targets is
  '네이버 블로그 포스팅과 검색 키워드별 순위 추적 대상';

comment on table public.blog_rank_history is
  '네이버 공식 블로그 API 및 실제 통합검색 VIEW 순위 수집 이력';
